### ISSUE TITLE
Tracking mode

### ISSUE THREAD

**Issue by kirushik** [kirushik/critical_chain#10]
- [x] support in model
- [x] toggle button in view
- [x] different partial sets rendering for estimation and tracking modes
- [x] no inline editing in tracking mode
- [x] additional (inline editable) elapsed values in tracking mode
- [x] Summation of elapsed values
